# To run: sudo docker-compose up -d

version: "3.8"
services:
    # define jupyter-server service
    jupyter-server:
        image: dl-jupyter
        init: true
        build:
            context: ./
            dockerfile: jupyter.Dockerfile
        env_file: ./.env
        ports:
            - ${JUPYTER_PORT}:${JUPYTER_PORT}
        volumes:
            - ${ROOT_DIR}:/jupyter
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        command:
            [
                "jupyter",
                "notebook",
                "--ip=*",
                "--port=${JUPYTER_PORT}",
                "--allow-root",
                "--notebook-dir=${JUPYTER_DIR}",
                '--NotebookApp.token=${JUPYTER_TOKEN}'
            ]
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: ["gpu"]
            
    # define tensorboard service
    tensorboard:
        image: dl-tensorboard
        build:
            context: ./
            dockerfile: tensorboard.Dockerfile
        ports:
            - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
        volumes:
            - ${ROOT_DIR}:/jupyter
        command:
            [
                "tensorboard",
                "--logdir=${TENSORBOARD_DIR}",
                "--port=${TENSORBOARD_PORT}",
                "--bind_all",
            ]